# Generated by Django 5.0.2 on 2024-02-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
