# Generated by Django 5.0.2 on 2024-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=30)),
                ('rolle', models.CharField(max_length=200)),
            ],
        ),
    ]
