# Generated by Django 5.0.2 on 2024-03-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_react'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
