# Generated by Django 5.0.2 on 2024-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_customerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
