# Generated by Django 5.0.2 on 2024-04-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_customerinfo_address_customerinfo_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1),
        ),
    ]
