# Generated by Django 5.0.2 on 2024-04-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_customerinfo_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='first_Name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='last_Name',
            new_name='lastName',
        ),
    ]
