# Generated by Django 5.0.2 on 2024-04-13 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0009_rename_first_name_customerinfo_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('d', 'done'), ('m', 'missed'), ('u', 'unspecified')], default='u', max_length=1)),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('manage_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receive_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CallbackNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('planned', models.DateTimeField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks_created', to=settings.AUTH_USER_MODEL)),
                ('link_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.customerinfo')),
                ('manage_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sended', models.DateTimeField()),
                ('content', models.CharField(max_length=5000)),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.customerinfo')),
            ],
        ),
    ]
