# Generated by Django 5.0.2 on 2024-04-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0010_call_callbacknotification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='gender',
            new_name='answer_type',
        ),
    ]
