# Generated by Django 5.0.2 on 2024-04-21 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0011_rename_gender_call_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='receive_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.customerinfo'),
        ),
    ]
