# Generated by Django 5.0.2 on 2024-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0012_alter_call_receive_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progess'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
