version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    depends_on:
      - frontend

  frontend:
    build: ./reactapp
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
